const mongoose = require("mongoose");

const EmpresaSchema = new mongoose.Schema(
  {
    empresa: {
      type: String,
    },
    endereco: {
      type: String,
    },
    email: {
      type: String,
    },
    11: [String],
    12: [String],
    13: [String],
    14: [String],
    18: [String],
    21: [String],
    26: [String],
    31: [String],
    31: [String],
    32: [String],
    32: [String],
    33: [String],
    34: [String],
    35: [String],
    36: [String],
    37: [String],
    42: [String],
    43: [String],
    45: [String],
    48: [String],
    51: [String],
    52: [String],
    55: [String],
    57: [String],
    61: [String],
    62: [String],
    63: [String],
    66: [String],
    68: [String],
    71: [String],
    72: [String],
    73: [String],
    75: [String],
    76: [String],
    78: [String],
    81: [String],
    82: [String],
    83: [String],
    85: [String],
    87: [String],
    88: [String],
  },
  { timestamps: true }
);
module.exports = mongoose.model("Empresa", EmpresaSchema);
